
databases:
- engine: PG
  name: convolys-app-db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
- cluster_name: convolys-app-redis
  engine: REDIS
  name: convolys-app-redis
  production: true
  version: "7"
name: convolys-app
region: nyc
services:
- dockerfile_path: Dockerfile.web
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${convolys-app-db.DATABASE_URL}
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: convolys-app.settings_production
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'MBScodSpTpnraySjFsGRBpNqFyltRfSogVSXMqTtRhyDTLoJkKlozjQodGcm'
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${convolys-app-redis.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: user/convolys-app
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: convolys-app-web
  routes:
  - path: /
workers:
- dockerfile_path: Dockerfile.web
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${convolys-app-db.DATABASE_URL}
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: convolys-app.settings_production
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'MBScodSpTpnraySjFsGRBpNqFyltRfSogVSXMqTtRhyDTLoJkKlozjQodGcm'
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${convolys-app-redis.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: user/convolys-app
  instance_count: 1
  instance_size_slug: basic-xs
  name: convolys-app-celery
  run_command: celery -A convolys-app worker -l INFO --pool=gevent --concurrency 2
